### ISSUE TITLE
Video Reactions and Comments Page

### ISSUE THREAD

**Issue by olvyko** [elrax/elrax#53]
### Summary

This is a tracking issue for the Video Reactions and Comments Page.

All sorts of possible reactions on video: likes/stars, shares, comments, follows, views, reports, "don't recommend".

### Steps

- [ ] Create server video likes/stars and view counter
- [ ] Create comments page UI
- [ ] Create server comments page logic and API
- [ ] Create share to mini-page
- [ ] Create report page UI
- [ ] Create report page server logic
- [ ] Create "don't recommend" server logic

### Unresolved Questions

* None yet.
